/** מוצרי דמו – האתר עובד גם בלי שרת מחובר (Vercel / build) */
export const FALLBACK_PRODUCTS = [
  {
    _id: 'demo-hair-remover',
    slug: 'hair-remover',
    category: 'hair-removal',
    title: 'מכשיר הסרת שיער עדין – שדרוג לשגרה שלך',
    headline: 'טיפוח חכם, פשוט ונגיש יותר',
    shortDescription: 'הסרת שיער נוחה בבית – בלי כאב, בקצב שלך.',
    hook: 'טיפוח עצמי צריך להיות פשוט וברור',
    context: 'שגרה לא עקבית מקשה לראות תוצאות לאורך זמן',
    solution: 'מוצרים חכמים שנועדו לפשט את שגרת הטיפוח',
    bullets: ['קל לשימוש ביום־יום', 'מותאם לשימוש ביתי', 'תוצאות עקביות', 'איכות גבוהה'],
    howItWorks: ['שימוש פשוט בבית', 'תוצאה הדרגתית ועקבית', 'שילוב קל בשגרה היומית'],
    price: 149,
    compareAtPrice: 249,
    stock: 18,
    images: [
      'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=800&q=80',
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80',
    ],
    reviews: [
      { name: 'נועה', rating: 5, text: 'עובד טוב, משתמשת כל יום', verifiedPurchase: true },
      { name: 'מיה', rating: 5, text: 'פשוט ונוח לשימוש', verifiedPurchase: true },
      { name: 'אלה', rating: 4, text: 'הגיע מהר ונראה איכותי', verifiedPurchase: true },
    ],
  },
  {
    _id: 'demo-facial-cleanser',
    slug: 'facial-cleanser',
    category: 'skin-care',
    title: 'סרום הזנה לפנים – שגרה רכה וברורה',
    headline: 'להרגיש טוב עם העור, כל יום',
    shortDescription: 'לחות ורכות – מוצר שמשתלב בשגרת הבוקר.',
    hook: 'טיפוח עצמי צריך להיות פשוט וברור',
    context: 'שגרה לא עקבית מקשה לראות תוצאות לאורך זמן',
    solution: 'מוצרים חכמים שנועדו לפשט את שגרת הטיפוח',
    bullets: ['קל למריחה', 'מתאים לכל סוגי העור', 'מרקם נעים', 'שגרה יומית קצרה'],
    howItWorks: ['מריחה על עור נקי', 'שימוש יומי קבוע', 'תחושת רעננות'],
    price: 89,
    compareAtPrice: 129,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80'],
    reviews: [
      { name: 'תמר', rating: 5, text: 'מרגיש איכותי ועובד טוב', verifiedPurchase: true },
      { name: 'שיר', rating: 5, text: 'נוח לשימוש, מרוצה מאוד', verifiedPurchase: true },
    ],
  },
  {
    _id: 'demo-sonic-brush',
    slug: 'sonic-brush',
    category: 'oral-care',
    title: 'מברשת שיניים סונית – ניקוי יסודי בבית',
    headline: 'שגרת פה נקייה ומרעננת',
    shortDescription: 'ניקוי עדין ויעיל – חוויה נעימה בכל בוקר.',
    hook: 'טיפוח עצמי צריך להיות פשוט וברור',
    context: 'שגרה לא עקבית מקשה לראות תוצאות לאורך זמן',
    solution: 'מוצרים חכמים שנועדו לפשט את שגרת הטיפוח',
    bullets: ['ניקוי יסודי', 'עדין לחניכיים', 'סוללה ארוכה', 'קל לתחזוקה'],
    howItWorks: ['הדלקה בלחיצה', 'החלקה על השיניים', 'שגרה של 2 דקות'],
    price: 119,
    compareAtPrice: 179,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=800&q=80'],
    reviews: [
      { name: 'דנה', rating: 5, text: 'הגיע מהר ועונה על הציפיות', verifiedPurchase: true },
    ],
  },
  {
    _id: 'demo-gua-sha',
    slug: 'gua-sha',
    category: 'tools',
    title: 'כלי גוואשה לעיסוי פנים – רגע של רוגע',
    headline: 'טיפוח שמרגיש כמו ספא בבית',
    shortDescription: 'עיסוי עדין שמעורר תחושת רעננות.',
    hook: 'טיפוח עצמי צריך להיות פשוט וברור',
    context: 'שגרה לא עקבית מקשה לראות תוצאות לאורך זמן',
    solution: 'מוצרים חכמים שנועדו לפשט את שגרת הטיפוח',
    bullets: ['אבן איכותית', 'קל לאחסון', 'מתאים לשגרה ערב', 'מתנה מושלמת'],
    howItWorks: ['מריחת שמן/סרום', 'עיסוי כלפי מעלה', '2–3 דקות ביום'],
    price: 69,
    compareAtPrice: 99,
    stock: 50,
    images: ['https://images.unsplash.com/photo-1515377901643-4a9748da9c6b?w=800&q=80'],
    reviews: [
      { name: 'יעל', rating: 5, text: 'מרגיש מפנק ואיכותי', verifiedPurchase: true },
    ],
  },
];

export const FALLBACK_STORE_SETTINGS = {
  storeName: 'Glow Routine',
  freeShippingBanner: { enabled: true, text: 'משלוח חינם על הזמנות מעל ₪149' },
  discountBanner: { enabled: false, text: '' },
};
